### ISSUE TITLE
undefined: meta.Name

### ISSUE THREAD

**Issue by cippaciong** [fsuhrau/buffalo-swagger#1]
Hi, I'm trying to install this tool but I get the following error:
```
go get -u github.com/fsuhrau/buffalo-swagger
# github.com/fsuhrau/buffalo-swagger/parser
.go/src/github.com/fsuhrau/buffalo-swagger/parser/parser.go:21:13: undefined: meta.Name
```

**Comment by fsuhrau** [comment]
buffalo changed the package for the route meta data from "meta" to "inflect".
updated the package on master branch.
